language: node_js
node_js:
  - 8.5.0
services:
  - mysql  

script:
  - "npm run dev"
  

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: backend-turing-nodejs
  on:
    repo: tksilicon/backend_challenge_template_master

  