language: node_js
node_js:
  - 8.5.0
services:
  - mysql
before_install:
  - mysql -u root --password="" < database/dump.sql
script:
  - "npm run test"
deploy:
  provider: heroku
  api_key:
    secure: 3d1959c4-9d87-448c-bd6f-79ff189b6079
  app: backend-turing-nodejs
  on:
    repo: tksilicon/backend_challenge_template_master

  